version: "3.7"

services:
  acorn_vehicle_test:
    extends:
      file: docker-compose-vehicle.yml
      service: acorn_vehicle
    volumes:
      - .:/home/pi/
      - ./.bashrc:/home/pi/.bashrc
    command: sleep infinity
